import "@styles/globals.css";
import Navbar from "@components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="gradient"></div>
        </div>

        <Navbar />

        <main className="app">{children}</main>
      </body>
    </html>
  );
}
